version: 2.1
jobs:
  build:
    docker:
      - image: my-k8s-app:dev
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker
          command: apt-get update && apt-get install -y docker.io
      - run:
          name: Build Docker Image
          command: |
            docker build -t samy2/my-k8s-app:dev .
      - run:
          name: Push Docker Image
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push samy2/my-k8s-app:dev
  deploy:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install kubectl
          command: |
            curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Deploy to Kubernetes
          command: |
            kubectl set image deployment/my-k8s-deployment my-container=samy2/my-k8s-app:dev